### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by ricardobalk** [ricardobalk/www#55]
TypeScript is a more strict language that transpiles to JavaScript, like Babel does with ES5+. The main benefit is that typescript also requires the correct types (`string`, `Object`, `Array`, `Number` to name some), which make the code more robust.

- Add TypeScript
- Convert existing code to TypeScript
- Merge into develop

An alternative would be ES5+ with Flow, in case it is difficult to set up. Flow allows to do type checking by code comments, so the code remains to work without Flow.

**Comment by ellipticcurv3** [comment]
https://github.com/Microsoft/TypeScript-Vue-Starter#typescript-vue-starter

**Comment by ricardobalk** [comment]
Working on this right now. I expect this to be finished by the end of the week (June 19, 2020).
